version: "3.9"
    
services:
  swag:
    image: lscr.io/linuxserver/swag
    container_name: smalldata-swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - URL=${URL}
      - SUBDOMAINS=wildcard
      - VALIDATION=duckdns
      - DUCKDNSTOKEN=${DUCKDNS_TOKEN}
      - CERTPROVIDER=zerossl
      - EMAIL=${EMAIL}
    volumes:
      - ${PWD}/data/swag/swag_config_store:/config
    restart: unless-stopped
    ports:
      - 443:443
      - 80:80 
    networks:
      swag:
    healthcheck:
      test: ["CMD", "cat", "/etc/letsencrypt/live/${URL}/privkey.pem"]
      interval: 10s
      timeout: 10s
      
networks:
  swag:
    driver: bridge
