version: "3.9"
services:
  proxy:
    image: jwilder/nginx-proxy
    container_name: gemini-proxy
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  whoami:
    environment:
      TZ: 'Europe/London'
      VIRTUAL_HOST: 'whoami.gemini-test.duckdns.org'
